services:
  postgres:
    image: postgres:16
    restart: on-failure
    container_name: my-postgres-container
    networks:
      - my_network
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    container_name: pgadmin
    networks:
      - my_network
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  custom-minio:
    image: custom-minio
    build:
      context: ./setup
      dockerfile: s3.dockerfile
    ports:
      - 9000:9000
      - 9001:9001
    container_name: minio-server-combined
    networks:
      - my_network

#  minio-server:
#    image: minio/minio
#    ports:
#      - 9000:9000
#      - 9001:9001
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#    container_name: minio-server
#    networks:
#      - my_network
#    env_file:
#      - .env
#    command: server /data --address ":9000" --console-address ":9001"
#    volumes:
#      - s3-data:/var/lib/minio/data
#
#  minio-client:
#    image: minio/mc
#    # minio should be up and running before this container starts
#    depends_on:
#      - minio-server
#    container_name: minio-client
#    networks:
#      - my_network
#    env_file:
#      - .env
#    entrypoint: >
#      /bin/sh -c "
#      /usr/bin/mc config;
#      /usr/bin/mc config host add myminio http://minio-server:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY} --insecure;
#      /usr/bin/mc mb myminio/data-bucket;
#      /usr/bin/mc policy set public myminio/data-bucket;
#      /usr/bin/mc cp --recursive /var/lib/minio/data myminio/data-bucket;
#      while true; do sleep 1000; done
#      "
#    volumes:
#      - s3-data:/var/lib/minio/data

volumes:
  postgres-data:
  pgadmin-data:
  s3-data:
  
networks:
  my_network: